# Generated by Django 2.1.3 on 2018-12-29 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import docker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Birth_Certificate', models.FileField(upload_to=docker.models.user_directory_path)),
                ('Degree_Certificate', models.FileField(upload_to=docker.models.user_directory_path)),
            ],
        ),
    ]
