# Generated by Django 2.1.3 on 2018-12-29 10:52

from django.db import migrations, models
import docker.models


class Migration(migrations.Migration):

    dependencies = [
        ('docker', '0002_documents_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='Birth_Certificate',
            field=models.FileField(upload_to=docker.models.user_directory_path, validators=[docker.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='documents',
            name='Degree_Certificate',
            field=models.FileField(upload_to=docker.models.user_directory_path, validators=[docker.models.validate_file_extension]),
        ),
    ]
